# Generated by Django 6.0.5 on 2026-05-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('college', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('tenth_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('twelfth_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ug', models.CharField(blank=True, max_length=100)),
                ('pg', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('internship', models.CharField(choices=[('Data Science', 'Data Science'), ('Python Development', 'Python Development'), ('Full Stack Development', 'Full Stack Development'), ('AI & ML', 'AI & ML'), ('Web Development', 'Web Development'), ('Cyber Security', 'Cyber Security')], max_length=100)),
                ('duration', models.CharField(choices=[('1 Month', '1 Month'), ('2 Months', '2 Months'), ('3 Months', '3 Months'), ('6 Months', '6 Months')], max_length=20)),
                ('payment_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Student Registration',
                'verbose_name_plural': 'Student Registrations',
                'db_table': 'student_registration',
            },
        ),
    ]
